#!/bin/bash

echo "🚀 SpectraSense - Quick Deploy to Render"
echo "========================================"
echo ""
echo "Your GitHub repo: https://github.com/SaaiAravindhRaja/SpectraSense"
echo ""
echo "📋 Quick Steps:"
echo ""
echo "1. Opening Render dashboard in your browser..."
echo ""
echo "2. Click 'New +' → 'Web Service'"
echo ""
echo "3. Connect GitHub and select: SaaiAravindhRaja/SpectraSense"
echo ""
echo "4. Configuration (auto-filled from render.yaml):"
echo "   ✓ Name: spectrasense-ai"
echo "   ✓ Runtime: Python 3"
echo "   ✓ Build: pip install -r requirements.txt"
echo "   ✓ Start: gunicorn app:app"
echo "   ✓ Plan: Free"
echo ""
echo "5. Click 'Create Web Service' → Wait 5-10 minutes"
echo ""
echo "6. Your app will be live at:"
echo "   🌐 https://spectrasense-ai.onrender.com"
echo ""
echo "========================================"
echo ""

# Open Render dashboard
open "https://dashboard.render.com/create?type=web"

echo "✨ Browser opened! Follow the steps above."
echo ""
echo "Need the full guide? Run: cat DEPLOYMENT.md"
