services:
  - type: web
    name: spectrasense-ai
    runtime: python
    # Upgrade packaging tools and prefer binary wheels to speed up installs
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8080
    healthCheckPath: /health
    autoDeploy: true
